spring:
  application:
    name: lost-hub
  config:
    import: optional:application-secret.yml
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  datasource:
    url: jdbc:postgresql://192.168.150.129:5432/lost_hub?currentSchema=public
    username: ${lost-hub.db.postgresql.username}
    password: ${lost-hub.db.postgresql.password}
  data:
    redis:
      host: 192.168.150.129
      port: 6379
      password: ${lost-hub.redis.password}
      timeout: 5s
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
jwt:
  user-secret: ${lost-hub.jwt.user-secret}
  admin-secret: ${lost-hub.jwt.admin-secret}
  expire-hours: ${lost-hub.jwt.expire-hours}

server:
  port: 8080

lost-hub:
  image-embedding:
    enabled: true
    dimension: 512
  websocket:
    allowed-origins: "*"
  trust-proxy-headers: false

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api/doc.html
    tags-sorter: alpha
    operations-sorter: alpha
    try-it-out-enabled: false


logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.hub.domain.po

langchain4j:
  open-ai:
    chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${lost-hub.ai.api-key}
      model-name: qwen-plus
      log-requests: false
      log-responses: false
    streaming-chat-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${lost-hub.ai.api-key}
      model-name: qwen-plus
      log-requests: false
      log-responses: false
    embedding-model:
      base-url: https://dashscope.aliyuncs.com/compatible-mode/v1
      api-key: ${lost-hub.ai.api-key}
      model-name: text-embedding-v4
      dimensions: 1024
      log-requests: false
      log-responses: false